name: semana7_castillo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_database: ^12.0.2
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  firebase_auth: ^6.1.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  url_launcher: ^6.1.10
  http: ^1.2.0 # ðŸ‘ˆ AÃ±adido para evitar el error en ubicacion_screen.dart
  flutter_polyline_points: 3.1.0
  shimmer: ^3.0.0 # <--- Agrega esto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
